PHONY += default
default:

PHONY += test
test:

PHONY += clean
clean:
	rm -rf

PHONY += test-all
test-all:
	$(MAKE) -C ../cabinet_inspector/ all
	../cabinet_inspector/cabinet_inspector

.PHONY: $(PHONY)
